import { OrganizationSettingsGet } from '@shared/models/organization-settings.model';

export const MockSettings: OrganizationSettingsGet[] = [
  {
    settingKey: "InternalAgencyApplies",
    name: "Internal Agency Applies",
    controlType: 1,
    value: "true",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: true,
    overridableByRegion: true,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 1
  },
  {
    settingKey: "AllowDNWInTimesheets",
    name: "Allow DNW In Timesheets",
    controlType: 1,
    value: "true",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: true,
    overridableByRegion: true,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 2
  },
  {
    settingKey: "EnableLTAConcept",
    name: "Enable LTA Concept",
    controlType: 1,
    value: "true",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: true,
    overridableByRegion: true,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 3
  },
  {
    settingKey: "EnableRegularLocalRates",
    name: "Enable Regular Local rates",
    controlType: 1,
    value: "true",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: false,
    overridableByRegion: true,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 4
  },
  {
    settingKey: "EnableInvoiceInterface",
    name: "Enable Invoice Interface",
    controlType: 1,
    value: "false",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: true,
    overridableByRegion: false,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 5
  },
  {
    settingKey: "OrderLockAndUnlock",
    name: "Order lock and unlock",
    controlType: 1,
    value: "false",
    valueOptions: null,
    organizationId: 1,
    regionId: null,
    regionName: null,
    locationId: null,
    locationName: null,
    departmentId: null,
    departmentName: null,
    overridableByOrganization: false,
    overridableByRegion: true,
    overridableByLocation: true,
    overridableByDepartment: true,
    orderPosition: 6
  }
]
