apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  hosts:
  - "{{ .Values.istio.domain }}"
  gateways:
    {{- if .Values.istio.backendgateway }}
    - "{{ .Values.istio.backendgateway }}"
    {{ else }}
    - {{ include "einsteinui.fullname" . }}
    {{- end }}
  http:
  - match:
    - uri:
        exact: "{{ .Values.istio.uriExact }}"
    - uri:
        prefix: "{{ .Values.istio.uriPrefix }}"
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "einsteinui.fullname" . }}