{{- if not .Values.istio.backendgateway -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - hosts:
    - "{{ .Values.istio.domain }}"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: "{{ .Values.istio.credentialName }}"
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
{{- end }}