apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  hosts:
  - "{{ .Values.istio.domain }}"
  gateways:
  - {{ include "einsteinui.fullname" . }}
  http:
  - match:
    - uri:
        exact: /ui
    - uri:
        prefix: /ui/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "einsteinui.fullname" . }}
        port:
          number: 80