apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  hosts:
  - "dev.einstein2.com"
  gateways:
  - {{ include "einsteinui.fullname" . }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        regex: "^(?!\\einsteinapi).*"
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "einsteinui.fullname" . }}
        port:
          number: 80