apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "einsteinui.fullname" . }}
  http:
  - match:
    - uri:
        exact: /einsteinui
    - uri:
        prefix: /einsteinui/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "einsteinui.fullname" . }}
        port:
          number: 80