apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "einsteinui.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "einsteinui.fullname" . }}
  http:
  - route:
    - destination:
        port:
          number: 80
        host: {{ include "einsteinui.fullname" . }}
  # - match:
  #   - uri:
  #       exact: /
  #   - uri:
  #       prefix: /
  #   rewrite:
  #     uri: /
  #   route:
  #   - destination:
  #       host: {{ include "einsteinui.fullname" . }}
  #       port:
  #         number: 80