export enum BillRateTitleId {
  Regular = 1,
  RegularLocal = 2,
  GuaranteedHours = 3,
  Callback = 4,
  Charge = 5,
  Holiday = 6,
  Oncall = 7,
  Orientation = 9,
  Preceptor = 10,
  Mileage = 11,
  DailyOT = 12,
  DailyPremiumOT = 13,
  WeeklyOT = 14,
  DayOT7th = 15,
  DayPremiumOT7th = 16,
  MissedMeal = 26,
  FacilityCalledOff = 27,
  ResourceCalledOff = 28,
}
