export const Topics = [
    'Dashboard',
    'Organization',
    'Organization List',
    'Associated Agencies',
    'Candidates',
    'Order Management',
    'Candidate Assignment',
    'Timesheets',
    'Invoices',
    'Reports',
    'Settings',
    'Agency',
    'Agency List',
    'Associated Organizations',
    'Candidates',
    'Order Management',
    'Candidate Assignment',
    'Timesheets',
    'Invoices',
    'Reports',
    'Settings',
    'MSP',
    'MSP List',
    'Reports',
    'Administration',
    'Roles & Permissions',
    'User List',
    'Notification Subscription',
    'Notification Templates',
    'Financial Module',
    'Master Data',
    'Analytics',
    'Client Finance Accrual Report',
    'Invoice Summary',
    'Aging Details',
    'Client Finance Report',
    'Credential Expiry',
    'Timesheet Report',
    'VMS Invoice Report',
    'Finance Report',
    'Fill Rate',
    'YTD Summary',
    'Missing Credentials',
    'Head Count',
    'Candidate Agency Status Report',
    'Candidate List',
    'Vendor Scorecard',
    'Job Event',
    'General Comments',
    'YTD Report',
    'Agency & Department Spent Hours',
    'Staffing Summary',
    'Predicted Contract Labor Spent',
    'Job Summary',
    'Event Log',
    'Missing Kronos ID s',
    'Benchmarking Rate By State',
    'Organization Invoice',
    'Job Compliance',
    'Job Fill Ratio',
    'Job Details',
    'Job Details Summary',
    'Labor Utilization',
    'Message History',
    'Order Check',
    'Overall Status',
    'Overtime',
    'Employees',
    'Employee List'
];
