export enum MobileMenuItems {
  Cancel = 'Cancel',
  Approve = 'Approve',
  Edit = 'Edit',
  CloseOrder = 'Close Order',
  ReOpen = 'Re-Open',
  CreateReOrder = 'Create Re-Order',
  Delete = 'Delete',
  Unlock = 'Unlock',
  Upload = 'Upload',
  Lock = 'Lock',
  Save = 'Save',
  Print = 'Print',
  Filters = 'Filters',
  Import = 'Import',
  ExportExel = 'Export Excel File',
  ExportCSV = 'Export CSV File',
  ExportCustom = 'Export Custom',
  Recalculate = 'Recalculate',
  AddRecord = 'Add Record',
}
