export enum TIERS_ACTIONS {
  GET_TIERS_BY_PAGE = '[tier] GET TIERS BY PAGE',
  SAVE_TIER = '[tier] SAVE TIER',
  SAVE_TIER_IRP = '[tier] SAVE TIER IRP',
  DELETE_TIER = '[tier] DELETE TIER',
  UPDATE_PAGE_AFTER_SUCCESS_ACTION = '[tier] UPDATE PAGE AFTER SUCCESS ACTION',
  SHOW_OVERRIDE_TIER_DIALOG = '[tier] SHOW OVERRIDE TIER DIALOG',
  CHANGE_TIER_PRIORITY = '[tier] CHANGE TIER PRIORITY',
  GET_WORKCOMMITMENT = '[tier] GET WORK COMMITMENT'
}
