import { FieldType, InputAttrType } from '@core/enums';
import { ControlTypes, ValueType } from '@shared/enums/control-types.enum';
import { ExportColumn } from '@shared/models/export.model';
import { LocationsSourceKeys, LocationsTrackKey } from './locations.enum';
import { LocationDialogConfig, LocationFilterConfig } from './locations.interface';

export const LocationInitFilters: LocationFilterConfig = {
  externalIds: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  invoiceIds: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  names: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  addresses1: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  cities: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  states: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  zipCodes: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  contactPeople: { type: ControlTypes.Multiselect, valueType: ValueType.Text, dataSource: [] },
  includeInIRP: { type: ControlTypes.Dropdown, valueType: ValueType.Id, dataSource: [] },
};

export const LocationExportColumns: ExportColumn[] = [
  { text: 'Ext Location ID', column: 'ExternalId' },
  { text: 'Invoice Location ID', column: 'InvoiceId' },
  { text: 'Location Name', column: 'Name' },
  { text: 'Business Line', column: 'BusinessLine' },
  { text: 'Address 1', column: 'Address1' },
  { text: 'Address 2', column: 'Address2' },
  { text: 'City', column: 'City' },
  { text: 'State', column: 'State' },
  { text: 'Zip', column: 'Zip' },
  { text: 'Contact Person', column: 'ContactPerson' },
];

export const LocationsExportIrpColumns: ExportColumn[] = [
  { text: 'Ext Location ID', column: 'ExternalId' },
  { text: 'Invoice Location ID', column: 'InvoiceId' },
  { text: 'Location Name', column: 'Name' },
  { text: 'Business Line', column: 'BusinessLine' },
  { text: 'Address 1', column: 'Address1' },
  { text: 'Address 2', column: 'Address2' },
  { text: 'City', column: 'City' },
  { text: 'State', column: 'State' },
  { text: 'Zip', column: 'Zip' },
  { text: 'Contact Person', column: 'ContactPerson' },
  { text: 'Include in IRP', column: 'IncludeInIRPText'},
];

export const MESSAGE_REGIONS_NOT_SELECTED = 'Region was not selected';

export const LocationsDialogConfig: LocationDialogConfig = {
  baseForm: [
    {
      field: 'externalId',
      title: 'Location Id',
      fieldType: FieldType.Input,
      gridAreaName: 'exteranlArea',
      required: false,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'invoiceId',
      title: 'Invoice Location ID',
      fieldType: FieldType.Input,
      gridAreaName: 'invoiceArea',
      required: true,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'name',
      title: 'Location Name',
      fieldType: FieldType.Input,
      gridAreaName: 'nameArea',
      required: true,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'businessLineId',
      title: 'Business Line',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.BusinessLineData,
      gridAreaName: 'businessLineArea',
      required: false,
      visible: true,
    },
    {
      field: 'locationType',
      title: 'Location Type',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.LocationTypes,
      gridAreaName: 'locationTypeArea',
      required: false,
      visible: true,
    },
    {
      field: 'timeZone',
      title: 'Time Zone',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.TimeZoneIds,
      gridAreaName: 'timeZoneArea',
      required: false,
      visible: true,
    },
    {
      field: 'address1',
      title: 'Address 1',
      fieldType: FieldType.Input,
      gridAreaName: 'address1Area',
      required: true,
      maxLen: 100,
      visible: true,
    },
    {
      field: 'address2',
      title: 'Address 2',
      fieldType: FieldType.Input,
      gridAreaName: 'address2Area',
      required: false,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'state',
      title: 'State',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.States,
      gridAreaName: 'stateArea',
      required: true,
      visible: true,
    },
    {
      field: 'city',
      title: 'City',
      fieldType: FieldType.Input,
      gridAreaName: 'cityArea',
      required: true,
      visible: true,
    },
    {
      field: 'zip',
      title: 'Zipcode',
      fieldType: FieldType.Input,
      gridAreaName: 'zipArea',
      required: true,
      maxLen: 6,
      pattern: '[0-9]*',
      visible: true,
    },
  ],
  subForms: [
    {
      formTitle: 'Contacts',
      trackKey: LocationsTrackKey.Contacts,
      containerClass: 'contacts-form',
      controls: [
        {
          field: 'contactPerson',
          title: 'Contact Person',
          fieldType: FieldType.Input,
          required: false,
          gridAreaName: 'personArea',
          maxLen: 50,
          visible: true,
        },
        {
          field: 'contactEmail',
          title: 'Contact Person Email',
          fieldType: FieldType.Input,
          required: false,
          gridAreaName: 'emailArea',
          inputType: InputAttrType.Mail,
          visible: true,
        },
        {
          field: 'phoneNumber',
          title: 'Phone Number',
          required: false,
          gridAreaName: 'phoneArea',
          fieldType: FieldType.Input,
          pattern: '^[0-9]*$',
          maxLen: 10,
          inputType: InputAttrType.Tel,
          visible: true,
        },
        {
          field: 'phoneType',
          title: 'Phone Type',
          required: false,
          gridAreaName: 'phoneTypeArea',
          fieldType: FieldType.Dropdown,
          sourceKey: LocationsSourceKeys.PhoneType,
          visible: true,
        },
        {
          field: 'ext',
          title: 'Ext',
          required: false,
          gridAreaName: 'extArea',
          fieldType: FieldType.Input,
          visible: true,
        },
        {
          field: 'glNumber',
          title: 'GL Number',
          required: false,
          gridAreaName: 'glArea',
          maxLen: 50,
          fieldType: FieldType.Input,
          visible: true,
        },
        {
          field: 'inactiveDate',
          title: 'Inactivation Date',
          required: false,
          gridAreaName: 'inactivateArea',
          fieldType: FieldType.Date,
          visible: true,
        },
        {
          field: 'reactivateDate',
          title: 'Reactivation Date',
          required: false,
          gridAreaName: 'reactivateArea',
          fieldType: FieldType.Date,
          visible: true,
        },
      ],
    },
  ],
};

export const LocationsDialogWithIrpConfig: LocationDialogConfig = {
  baseForm: [
    {
      field: 'externalId',
      title: 'Location Id',
      fieldType: FieldType.Input,
      gridAreaName: 'exteranlArea',
      required: false,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'includeInIRP',
      title: 'Include in IRP',
      fieldType: FieldType.Toggle,
      gridAreaName: 'irpArea',
      required: false,
      visible: true,
    },
    {
      field: 'invoiceId',
      title: 'Invoice Location ID',
      fieldType: FieldType.Input,
      gridAreaName: 'invoiceArea',
      required: true,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'name',
      title: 'Location Name',
      fieldType: FieldType.Input,
      gridAreaName: 'nameArea',
      required: true,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'businessLineId',
      title: 'Business Line',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.BusinessLineData,
      gridAreaName: 'businessLineArea',
      required: false,
      visible: true,
    },
    {
      field: 'timeZone',
      title: 'Time Zone',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.TimeZoneIds,
      gridAreaName: 'timeZoneArea',
      required: false,
      visible: true,
    },
    {
      field: 'address1',
      title: 'Address 1',
      fieldType: FieldType.Input,
      gridAreaName: 'address1Area',
      required: true,
      maxLen: 100,
      visible: true,
    },
    {
      field: 'address2',
      title: 'Address 2',
      fieldType: FieldType.Input,
      gridAreaName: 'address2Area',
      required: false,
      maxLen: 50,
      visible: true,
    },
    {
      field: 'state',
      title: 'State',
      fieldType: FieldType.Dropdown,
      sourceKey: LocationsSourceKeys.States,
      gridAreaName: 'stateArea',
      required: true,
      visible: true,
    },
    {
      field: 'city',
      title: 'City',
      fieldType: FieldType.Input,
      gridAreaName: 'cityArea',
      required: true,
      visible: true,
    },
    {
      field: 'zip',
      title: 'Zipcode',
      fieldType: FieldType.Input,
      gridAreaName: 'zipArea',
      required: true,
      maxLen: 6,
      pattern: '[0-9]*',
      visible: true,
    },
  ],
  subForms: [
    {
      formTitle: 'Contacts',
      trackKey: LocationsTrackKey.Contacts,
      containerClass: 'contacts-form',
      controls: [
        {
          field: 'contactPerson',
          title: 'Contact Person',
          fieldType: FieldType.Input,
          required: false,
          gridAreaName: 'personArea',
          maxLen: 50,
          visible: true,
        },
        {
          field: 'contactEmail',
          title: 'Contact Person Email',
          fieldType: FieldType.Input,
          required: false,
          gridAreaName: 'emailArea',
          inputType: InputAttrType.Mail,
          visible: true,
        },
        {
          field: 'phoneNumber',
          title: 'Phone Number',
          required: false,
          gridAreaName: 'phoneArea',
          fieldType: FieldType.Input,
          pattern: '^[0-9]*$',
          maxLen: 10,
          inputType: InputAttrType.Tel,
          visible: true,
        },
        {
          field: 'phoneType',
          title: 'Phone Type',
          required: false,
          gridAreaName: 'phoneTypeArea',
          fieldType: FieldType.Dropdown,
          sourceKey: LocationsSourceKeys.PhoneType,
          visible: true,
        },
        {
          field: 'ext',
          title: 'Ext',
          required: false,
          gridAreaName: 'extArea',
          fieldType: FieldType.Input,
          visible: true,
        },
        {
          field: 'glNumber',
          title: 'GL Number',
          required: false,
          gridAreaName: 'glArea',
          maxLen: 50,
          fieldType: FieldType.Input,
          visible: true,
        },
        {
          field: 'inactiveDate',
          title: 'Inactivation Date',
          required: false,
          gridAreaName: 'inactivateArea',
          fieldType: FieldType.Date,
          visible: true,
        },
        {
          field: 'reactivateDate',
          title: 'Reactivation Date',
          required: false,
          gridAreaName: 'reactivateArea',
          fieldType: FieldType.Date,
          visible: true,
        },
      ],
    },
  ],
};

export const FieldsToHideInIrp: string[] = ['invoiceId'];

export const FieldsToHideInVms: string[] = ['includeInIRP'];

export const ExportImportColumnsToHideInIrp: string[] = ['InvoiceId'];

export const ExportImportColumnsToHideInVms: string[] = ['IncludeInIRPText'];
