export enum TIMESHEETS_ACTIONS {
  GET_TIMESHEETS = '[timesheets] GET TIMESHEETS',
  GET_PROFILE_TIMESHEETS = '[timesheets] GET PROFILE TIMESHEETS',
  OPEN_PROFILE = '[timesheets] OPEN PROFILE',
  OPEN_PROFILE_TIMESHEET_EDIT_DIALOG = '[timesheets] OPEN PROFILE TIMESHEET EDIT DIALOG',
  OPEN_PROFILE_TIMESHEET_ADD_DIALOG = '[timesheets] OPEN PROFILE TIMESHEETS ADD DIALOG',
  CLOSE_PROFILE_TIMESHEET_EDIT_DIALOG = '[timesheets] CLOSE PROFILE TIMESHEET EDIT DIALOG',
}

export enum TIMETHEETS_STATUSES {
  PENDING_APPROVE = 'pending apr.',
  MISSING = 'missing',
  ORG_APPROVED = 'org. approved',
  REJECTED = 'rejected',
}
export enum ProfileTimeSheetActionType {
  Add = 'add',
  Edit = 'edit',
}
