export enum TIERS_EXCEPTION_ACTION {
  GET_ASSOCIATE_LIST = '[associate] Get Associate List by Page',
  DELETE_ORG_AGENCY_BY_ID = '[associate] Delete Associate Organizations/Agency By ID ',
  SAVE_FEE_EXCEPTIONS = '[associate] Save Fee Exceptions',
  GET_ASSOCIATE_AGENCY_ORG = '[associate] Get Associate Agency / Org',
  INVITE_ORG_AGENCY = '[associate] Invite Organizations / Agency',
  INVITE_ORG_SUCCESS = '[associate] Invate Organizations Succeeded',
  SAVE_FEE_EXCEPTION_SUCCESS = '[associate] Save Fee Exceptions Succeeded',
  GET_ASSOCIATE_AGENCY_ORG_BY_ID = '[associate] Get Fee Setting By Organization / Agency Id',
  SAVE_PARTNERSHIP_SETTINGS = '[associate] Save Partnership Settings',
  UPDATE_ASSOCIATE_AGENCY_ORG_PAGE = '[associate] Update Associate Organizations Page',
  GET_PARTNERSHIP_SETTINGS_BY_ID = '[associate] Get Partnership Settings By Organization Id',
  SAVE_BASE_FEE = '[associate] Save Base Fee',
  GET_FEE_INITIAL_DATA = '[associate] Get Fee Exceptions Initial Data',
  GET_DISTRIBUTION_INITIAL_DATA = '[associate] Get Job Distribution Initial Data',
  REMOVE_FEE_EXC_BY_ID = '[associate] Remove Fee Exceptions By Id',
  GET_TIERS = '[associate] Get Tiers',
  SAVE_TIER_EXCEPTION = '[associate] Save Tier Exception',
  GET_TIER_EXCEPTION_BY_PAGE = '[associate] Get Tier Exception by Page',
  DELETE_TIER_EXCEPTION = '[associate] Delete Tier Exception',
  SELECTED_ORG_AGENCY = '[associate] Get Selected Org/Agency',
  UPDATE_PAGE_AFTER_SUCCESS_ACTION = '[associate] update page after success action',
  SAVE_TIER = '[associate] Save Tier',
  GET_GENERAL_TIERS = '[associate] Get General Tiers',
}
