export enum FilterPageName {
  Empty = 0,
  OrderManagementVMSOrganization = 1,
  OrderManagementVMSAgency = 2,
  OrderManagementIRPOrganization = 3,
  OrderManagementIRPAgency = 4,
  CandidatesVMSOrganization = 5,
  CandidatesVMSAgency = 6,
  CandidatesIRPOrganization = 7,
  CandidatesIRPAgency = 8,
  CandidateAssignmentVMSOrganization = 9,
  CandidateAssignmentVMSAgency = 10,
  CandidateAssignmentIRPOrganization = 11,
  CandidateAssignment = 12,
  TimesheetsVMSOrganization = 13,
  TimesheetsVMSAgency = 14,
  TimesheetsIRPOrganization = 15,
  TimesheetsIRPAgency = 16,
  InvoicesVMSOrganization = 17,
  InvoicesVMSAgency = 18,
  InvoicesIRPOrganization = 19,
  SchedullerOrganization = 20,
  EmployeeOpenJobs = 21
}
