import { ItemModel } from '@syncfusion/ej2-splitbuttons/src/common/common-model';

import { ITabConfigInterface } from '../interface/i-tab-config.interface';
import { ITimesheet } from '../interface/i-timesheet.interface';
import { ExportType, TIMETHEETS_STATUSES } from '../enums/timesheets.enum';
import { HourOccupationType } from "../enums/hour-occupation-type.enum";


export const TAB_ADMIN_TIMESHEETS: ITabConfigInterface[] = [
  {
    title: 'All Timesheets',
  },
  {
    title: 'Pending Approval',
    amount: 2,
  },
  {
    title: 'Missing',
    amount: 6,
  },
  {
    title: 'Rejected',
    amount: 5,
  }
];

export const exportOptions: ItemModel[] = [
  { text: ExportType.Excel_file, id: '0' },
  { text: ExportType.CSV_file, id: '1' },
  { text: ExportType.Custom, id: '2' }
];

export const MOK_TIMESHEETS: ITimesheet[] = [
  {
    id: 1,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-01',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 2,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.ORG_APPROVED,
    orderId: '22-30-02',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 3,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.MISSING,
    orderId: '22-30-03',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 4,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.REJECTED,
    orderId: '22-30-04',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 5,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-05',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 6,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-06',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 7,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-07',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 8,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-08',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 9,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-09',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 10,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-10',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 11,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-11',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 12,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-12',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 13,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-13',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 14,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-14',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 15,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-15',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 16,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-16',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 17,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-17',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 18,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-18',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 19,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-19',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 20,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-20',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 21,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-21',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 22,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-22',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 23,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-23',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 24,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-24',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 25,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-25',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 26,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-26',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 27,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-27',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 28,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-28',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 29,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-29',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 30,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-30',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 31,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.PENDING_APPROVE,
    orderId: '22-30-31',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
  {
    id: 32,
    name: 'Brooklyn Simm',
    statusText: TIMETHEETS_STATUSES.REJECTED,
    orderId: '22-30-32',
    skillName: 'Certified Nursed Assistant',
    workWeek: '4 - WE 02/20/2022',
    departmentName: 'Emergency Department',
    billRate: 10.10,
    agencyName: 'AB Staffing',
    totalHours: 32,
  },
];

export const profileDetailsHoursChartColors = [
  '#FFFFFF',
  '#D8E5FF',
  '#B2CCFF',
  '#9EBFFF',
  '#6499FF',
  '#518CFF',
  '#3E7FFF',
];

export const profileDetailsHoursChartColorsMap: Record<HourOccupationType, string> = {
  [HourOccupationType.OnCall]: '#3E7FFF',
  [HourOccupationType.Callback]: '#518CFF',
  [HourOccupationType.Regular]: '#6499FF',
  [HourOccupationType.Holiday]: '#9EBFFF',
  [HourOccupationType.Charge]: '#B2CCFF',
  [HourOccupationType.Preceptor]: '#D8E5FF',
  [HourOccupationType.Orientation]: '#FFFFFF',
};
