export const ORG_SETTINGS: { [key: string]: Object }[] = [
  { text: 'Regions', id: 11, route: './regions' },
  { text: 'Locations', id: 2, route: './locations' },
  { text: 'Departments', id: 1, route: './departments' },
  { text: 'Shifts', id: 5, route: './shifts' },
  { text: 'Skills', id: 3, route: './skills'},
  { text: 'Credentials', id: 4, route: './credentials' },
  { text: 'Holidays', id: 7, route: './holidays' },
  { text: 'Workflow', id: 8, route: './workflow' },
  { text: 'Bill Rates', id: 9, route: './bill-rates' },
  { text: 'Configurations', id: 6, route: './settings' },
  { text: 'Reasons', id: 10, route: './reasons' },
  { text: 'Special Project', id: 12, route: './specialproject' },
  { text: 'Business Lines', id: 13, route: './businesslines' },
];
