import { FieldType } from '@core/enums';
import { FieldSettingsModel } from '@syncfusion/ej2-angular-dropdowns';
import { CommitmentDialogConfig } from '../interfaces';

export const CommitmentsDialogConfig = (): CommitmentDialogConfig => ({
  title: 'Add Commitment',
  editTitle: 'Edit Commitment',
  fields: [
    {
      field: 'masterWorkCommitmentId',
      title: 'Name',
      disabled: false,
      required: true,
      type: FieldType.Dropdown,
      disableOnEdit: true,
    },
    {
      field: 'regions',
      title: 'Region',
      disabled: false,
      required: true,
      type: FieldType.MultiSelectDropdown,
      dataSource: [],
      disableOnEdit: false,
    },
    {
      field: 'locations',
      title: 'Location',
      disabled: false,
      required: true,
      type: FieldType.MultiSelectDropdown,
      dataSource: [],
      disableOnEdit: false,
    },
    {
      field: 'skillIds',
      title: 'Skill',
      disabled: false,
      required: true,
      type: FieldType.MultiSelectDropdown,
      dataSource: [],
      disableOnEdit: false,
    },
    {
      field: 'availabilityRequirement',
      title: 'Availability Requirement (h)',
      disabled: false,
      required: false,
      type: FieldType.Number,
      decimals: 1,
      disableOnEdit: false,
    },
    {
      field: 'schedulePeriod',
      title: 'Schedule Period (Weeks)',
      disabled: false,
      required: false,
      type: FieldType.Number,
      decimals: 0,
      disableOnEdit: false,
    },
    {
      field: 'minimumWorkExperience',
      title: 'Min. Work Experience',
      disabled: false,
      required: false,
      type: FieldType.Number,
      decimals: 1,
      disableOnEdit: false,
    },
    {
      field: 'criticalOrder',
      title: 'Critical Order',
      disabled: false,
      required: false,
      type: FieldType.Number,
      decimals: 0,
      disableOnEdit: false,
    },
    {
      field: 'holiday',
      title: 'Holiday',
      disabled: false,
      required: false,
      type: FieldType.Dropdown,
      dataSource: [],
      disableOnEdit: false,
    },
    {
      field: 'startDate',
      title: 'Start Date',
      disabled: false,
      required: true,
      type: FieldType.Calendar,
      disableOnEdit: false,
    },
    {
      field: 'endDate',
      title: 'End Date',
      disabled: false,
      required: false,
      type: FieldType.Calendar,
      disableOnEdit: false,
    },
    {
      field: 'jobCode',
      title: 'Job Code',
      disabled: false,
      required: true,
      type: FieldType.Input,
      maxLength: 20,
      disableOnEdit: false,
    },
    {
      field: 'comments',
      title: 'Comment',
      disabled: false,
      required: false,
      type: FieldType.Input,
      maxLength: 200,
      disableOnEdit: false,
    },
  ],
});

export const OPTION_FIELDS: FieldSettingsModel = { text: 'name', value: 'id' };
