export enum WidgetTypeEnum {
  CANDIDATES = 'Candidates',
  APPLICANTS_BY_REGION = 'Applicants_by_Region',
  APPLICANTS_BY_POSITIONS = 'Applicants_by_Positions',
  POSITIONS_BY_TYPES = 'Open_Onboard_and_Closed_Positions',
  IN_PROGRESS_POSITIONS = 'In_Progress_Positions',
  OPEN_POSITIONS = 'Open_Positions',
  FILLED_POSITIONS = 'Filled_Positions',
  ACTIVE_POSITIONS = 'Active_Positions',
  AVERAGE_DAY_ACTIVE_POSITIONS = 'Average_Day_Of_Active_Positions',
  FILLED_POSITIONS_TREND = 'Filled_Positions_Trend',
  OPEN_POSITIONS_TREND = 'Open_Positions_Trend',
  IN_PROGRESS_POSITIONS_TREND = 'In_Progress_Positions_Trend',
  LTA_ORDER_ENDING = 'LTA_Order_Ending',
  Candidate_Applied_In_Last_N_Days = 'Candidate_Applied_In_Last_N_Days',
  ORG = 'Organization_Widget',
  AGENCY_POSITION_COUNT = "Position_count_for_Agency",
  RN_UTILIZATION ="RN_UTILIZATION",
  ALREADY_EXPIRED_CREDS = 'Already_expired_creds',
  UPCOMING_EXP_CREDS = 'Upcoming_exp_creds',
  AVAILABLE_EMPLOYEE = 'Available_Employee',
  CANDIDATES_ACTIVE_POSITIONS="Candidates_Active_Positions",
}
