export enum WidgetDescriptionEnum {
  CANDIDATES = 'Count of Active Candidates by Statuses',
  APPLICANTS_BY_REGION = 'Statewise Applicant Density',
  APPLICANTS_BY_POSITIONS = 'Statewise Applicant Density',
  POSITIONS_BY_TYPES = 'Open, In Progress, Filled and Close Positions over a time period',
  IN_PROGRESS_POSITIONS = 'In Progress Positions',
  OPEN_POSITIONS = 'Open Positions',
  FILLED_POSITIONS = 'Filled positions for active orders',
  ACTIVE_POSITIONS = 'Active Positions by Status',
  TASKS = 'Tasks_widget',
  FILLED_POSITIONS_TREND = 'Filled_Positions_Trend',
  CHAT = 'Chat_widget',
  INVOICES = 'Invoces_widget',
  OPEN_POSITIONS_TREND = 'Open_Positions_Trend',
  IN_PROGRESS_POSITIONS_TREND = 'In_Progress_Positions_Trend',
}
